on: [push]
name: "Ziply CI"
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2

      - name: "Build the tests."
        run: zig build test

      - name: "Run the tests."
        run: zig test src/tests.zig

      - name: "Generate documentation."
        run: zig build-lib -femit-docs src/root.zig

      - name: "Deploy the documentation."
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs
